name: Release Python Package

on:
  push:
    branches: [ main ]

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v3
      with:
        python-version: '3.8'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python3 -m pip install --upgrade build
        pip install requests setuptools wheel twine
    - name: Check CURRENT vs RELEASED version
      run: |
        echo | python .scripts/release_indicator.py >> $GITHUB_ENV
    - name: Release to PIPY when version bumped
      env:
        TWINE_USERNAME: __token__
        TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
      if: env.RELEASE_TO_PIPY == 'true'
      run: |
        python -m build
        twine upload dist/*
